// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'member_model.dart';

// **************************************************************************
// JsonSerializableGenerator
// **************************************************************************

Member _$MemberFromJson(Map<String, dynamic> json) => Member(
  memberId: json['memberId'] as String?,
  name: json['name'] as String?,
  portrait: json['portrait'] as String?,
  aiPortrait: json['aiPortrait'] as String?,
  cover: json['cover'] as String?,
  gender: (json['gender'] as num?)?.toInt(),
  age: (json['age'] as num?)?.toInt(),
  audit: json['audit'] as String?,
  birthday: json['birthday'] as String?,
  voice: json['voice'] as String?,
  voiceDuration: (json['voiceDuration'] as num?)?.toInt(),
  address: json['address'] as String?,
  city: json['city'] as String?,
  ic: json['ic'] as String?,
  email: json['email'] as String?,
  mobile: json['mobile'] as String?,
  signature: json['signature'] as String?,
  tags: json['tags'] as String?,
  source: json['source'] as String?,
  uid: json['uid'] as String?,
  recommend: (json['recommend'] as num?)?.toInt(),
  assistant: json['assistant'] as String?,
  purposeChatTime: json['purposeChatTime'] as String?,
  inviterCode: json['inviterCode'] as String?,
  roles: json['roles'] as String?,
);

Map<String, dynamic> _$MemberToJson(Member instance) => <String, dynamic>{
  'memberId': instance.memberId,
  'name': instance.name,
  'portrait': instance.portrait,
  'aiPortrait': instance.aiPortrait,
  'cover': instance.cover,
  'gender': instance.gender,
  'age': instance.age,
  'audit': instance.audit,
  'birthday': instance.birthday,
  'voice': instance.voice,
  'voiceDuration': instance.voiceDuration,
  'address': instance.address,
  'city': instance.city,
  'ic': instance.ic,
  'email': instance.email,
  'mobile': instance.mobile,
  'signature': instance.signature,
  'tags': instance.tags,
  'source': instance.source,
  'uid': instance.uid,
  'recommend': instance.recommend,
  'assistant': instance.assistant,
  'purposeChatTime': instance.purposeChatTime,
  'inviterCode': instance.inviterCode,
  'roles': instance.roles,
};

MemberAudit _$MemberAuditFromJson(Map<String, dynamic> json) => MemberAudit(
  loop: (json['loop'] as num?)?.toInt(),
  interval: (json['interval'] as num?)?.toInt(),
  audit: json['audit'] as String?,
);

Map<String, dynamic> _$MemberAuditToJson(MemberAudit instance) =>
    <String, dynamic>{
      'loop': instance.loop,
      'interval': instance.interval,
      'audit': instance.audit,
    };

Balance _$BalanceFromJson(Map<String, dynamic> json) => Balance(
  id: (json['id'] as num?)?.toInt(),
  memberId: json['member_id'] as String?,
  name: json['name'] as String?,
  portrait: json['portrait'] as String?,
  aiPortrait: json['ai_portrait'] as String?,
  cover: json['cover'] as String?,
  gender: (json['gender'] as num?)?.toInt(),
  age: (json['age'] as num?)?.toInt(),
  birthday: json['birthday'] as String?,
  voice: json['voice'] as String?,
  voiceDuration: (json['voice_duration'] as num?)?.toInt(),
  address: json['address'] as String?,
  city: json['city'] as String?,
  ic: json['ic'] as String?,
  email: json['email'] as String?,
  mobile: json['mobile'] as String?,
  signature: json['signature'] as String?,
  tags: json['tags'] as String?,
  source: json['source'] as String?,
  uid: json['uid'] as String?,
  recommend: (json['recommend'] as num?)?.toInt(),
  assistant: json['assistant'] as String?,
  purposeChatTime: json['purpose_chat_time'] as String?,
  inviterCode: json['inviter_code'] as String?,
  roles: json['roles'] as String?,
  channel: json['channel'] as String?,
  platform: json['platform'] as String?,
  guid: json['guid'] as String?,
  ip: json['ip'] as String?,
  chatLanguage: json['chat_language'] as String?,
  credit: (json['credit'] as num?)?.toInt(),
  password: json['password'] as String?,
  activate: (json['activate'] as num?)?.toInt(),
  audit: json['audit'] as String?,
  verify: json['verify'] as String?,
  createTime: (json['create_time'] as num?)?.toInt(),
  updateTime: (json['update_time'] as num?)?.toInt(),
  stripeCustomerId: json['stripe_customer_id'] as String?,
  webId: (json['web_id'] as num?)?.toInt(),
  px: json['px'] as String?,
  fcid: json['fcid'] as String?,
  adUkey: json['ad_ukey'] as String?,
  gpsAdid: json['gps_adid'] as String?,
  adId: json['ad_id'] as String?,
  country: json['country'] as String?,
  network: json['network'] as String?,
  payId: (json['pay_id'] as num?)?.toInt(),
  sourceType: (json['source_type'] as num?)?.toInt(),
  adName: json['ad_name'] as String?,
);

Map<String, dynamic> _$BalanceToJson(Balance instance) => <String, dynamic>{
  'id': instance.id,
  'member_id': instance.memberId,
  'name': instance.name,
  'portrait': instance.portrait,
  'ai_portrait': instance.aiPortrait,
  'cover': instance.cover,
  'gender': instance.gender,
  'age': instance.age,
  'birthday': instance.birthday,
  'voice': instance.voice,
  'voice_duration': instance.voiceDuration,
  'address': instance.address,
  'city': instance.city,
  'ic': instance.ic,
  'email': instance.email,
  'mobile': instance.mobile,
  'signature': instance.signature,
  'tags': instance.tags,
  'source': instance.source,
  'uid': instance.uid,
  'recommend': instance.recommend,
  'assistant': instance.assistant,
  'purpose_chat_time': instance.purposeChatTime,
  'inviter_code': instance.inviterCode,
  'roles': instance.roles,
  'channel': instance.channel,
  'platform': instance.platform,
  'guid': instance.guid,
  'ip': instance.ip,
  'chat_language': instance.chatLanguage,
  'credit': instance.credit,
  'password': instance.password,
  'activate': instance.activate,
  'audit': instance.audit,
  'verify': instance.verify,
  'create_time': instance.createTime,
  'update_time': instance.updateTime,
  'stripe_customer_id': instance.stripeCustomerId,
  'web_id': instance.webId,
  'px': instance.px,
  'fcid': instance.fcid,
  'ad_ukey': instance.adUkey,
  'gps_adid': instance.gpsAdid,
  'ad_id': instance.adId,
  'country': instance.country,
  'network': instance.network,
  'pay_id': instance.payId,
  'source_type': instance.sourceType,
  'ad_name': instance.adName,
};
